import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import FooterCom from "@/components/FooterCom";
import Provider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>

       <div className="bg-white dark:bg-slate-900">
       <Navbar/>
        {children}
        <FooterCom/>
       </div>
        </Provider>
        </body>
    </html>
  );
}
